unique_ids:
  assets:
    standard-page.html: GW7SPAYHLFWIDCWBWHQH65XYXYN6UBY3
    theme.css: 4S7ZFYX6U56M5RP2OHX3OT7VIQSGYLZY
  forms:
    Form1: 4PBMJEDEDKSYRT3T65JPMMMH7UIFO5FU
  modules: {}
  scripts: {}
  server_modules: {}
